---
- name: Configure Docker host for Wazuh Docker event monitoring
  hosts: endpoints
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure Wazuh agent configuration directory exists
      file:
        path: /var/ossec/etc
        state: directory

    - name: Configure Docker container runtime logs in ossec.conf
      blockinfile:
        path: /var/ossec/etc/ossec.conf
        marker: "<!-- {mark} ANSIBLE DOCKER CONTAINER LOG CONFIG -->"
        block: |
          <localfile>
            <log_format>syslog</log_format>
            <location>/var/lib/docker/containers/*/*-json.log</location>
          </localfile>
        insertbefore: "</ossec_config>"
      notify: Restart Wazuh Agent

  handlers:
    - name: Restart Wazuh Agent
      systemd:
        name: wazuh-agent
        state: restarted
