---
- name: Ensure remote commands are enabled in Wazuh agent
  hosts: endpoints
  become: yes
  gather_facts: yes
  tasks:
    - name: Ensure /var/ossec/etc/local_internal_options.conf exists
      ansible.builtin.file:
        path: /var/ossec/etc/local_internal_options.conf
        state: touch
        mode: '0644'

    - name: Check if wazuh_command.remote_commands is already set
      ansible.builtin.lineinfile:
        path: /var/ossec/etc/local_internal_options.conf
        line: "wazuh_command.remote_commands=1"
        state: present
      register: wazuh_config

    - name: Restart Wazuh agent if config was changed
      ansible.builtin.service:
        name: wazuh-agent
        state: restarted
      when: wazuh_config.changed
