// pkg/consul/agent/cloudinit.go
//
// Cloud-init generation for Consul agent deployment in VMs.
// Migrated from pkg/kvm/consul_autoregister.go with improvements.
//
// Last Updated: 2025-01-24

package agent

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/CodeMonkeyCybersecurity/eos/pkg/consul"
	"github.com/CodeMonkeyCybersecurity/eos/pkg/eos_io"
	"github.com/CodeMonkeyCybersecurity/eos/pkg/shared"
	"github.com/uptrace/opentelemetry-go-extra/otelzap"
	"go.uber.org/zap"
)

// GenerateCloudInit creates cloud-init YAML configuration for Consul agent deployment.
//
// This function generates a complete cloud-init configuration that:
//   - Installs Consul binary from HashiCorp releases
//   - Creates system user and directories with correct permissions
//   - Generates HCL configuration file
//   - Sets up systemd service
//   - Configures service registration
//   - Stores metadata in Consul K/V
//
// The generated cloud-init is standalone and can be:
//   - Written to user-data for cloud-init ISO
//   - Merged with existing cloud-init configurations
//   - Used in cloud platforms (AWS, GCP, Azure)
//
// All values use centralized constants from pkg/consul/constants.go
// No hardcoded paths, ports, or permissions.
//
// Parameters:
//   - rc: RuntimeContext for logging
//   - config: Agent configuration
//
// Returns:
//   - string: Complete cloud-init YAML
//   - error: Any generation error
func GenerateCloudInit(rc *eos_io.RuntimeContext, config AgentConfig) (string, error) {
	logger := otelzap.Ctx(rc.Ctx)

	// Validate required fields
	if config.NodeName == "" {
		return "", fmt.Errorf("node_name is required")
	}
	if config.Datacenter == "" {
		return "", fmt.Errorf("datacenter is required")
	}

	logger.Info("Generating cloud-init for Consul agent",
		zap.String("node_name", config.NodeName),
		zap.String("datacenter", config.Datacenter),
		zap.String("mode", string(config.Mode)))

	// Set defaults
	if config.LogLevel == "" {
		config.LogLevel = "INFO"
	}
	if config.Environment == "" {
		config.Environment = "default"
	}

	// Calculate paths
	binaryDir := filepath.Dir(consul.ConsulBinaryPath)
	servicesHCLPath := filepath.Join(consul.ConsulConfigDir, "services.hcl")

	// Generate cloud-init template
	cloudInit := fmt.Sprintf(`#cloud-config

# Hostname configuration
hostname: %s
fqdn: %s.%s.consul

# Package updates
package_update: true
package_upgrade: false

# Install required packages
packages:
  - curl
  - unzip
  - jq

# Install and configure Consul
runcmd:
  # Install Consul binary
  - curl -fsSL https://releases.hashicorp.com/consul/%s/consul_%s_linux_amd64.zip -o /tmp/consul.zip
  - unzip -o /tmp/consul.zip -d %s
  - chmod +x %s
  - rm /tmp/consul.zip

  # Create Consul directories
  - mkdir -p %s
  - mkdir -p %s
  - mkdir -p %s

  # Create consul user
  - useradd --system --home %s --shell /bin/false %s || true
  - chown -R %s:%s %s
  - chown -R %s:%s %s
  - chown -R %s:%s %s

write_files:
  # Consul configuration
  - path: %s
    owner: %s:%s
    permissions: '%04o'
    content: |
      # Generated by Eos for VM: %%s
      # Environment: %%s
      # Datacenter: %%s

      datacenter = "%%s"
      data_dir = "%s"
      log_file = "%s"
      log_level = "%s"

      # Client configuration
      client_addr = "0.0.0.0"
      bind_addr = "{{ GetDefaultPrivateIP }}"

      # Retry join - connect to Consul servers
      retry_join = [%%s]

      # Node metadata
      node_name = "%%s"
      node_meta = {
        "vm_name" = "%%s"
        "environment" = "%%s"
        "managed_by" = "eos"
        "created_at" = "{{ timestamp }}"
      }

      # Performance tuning
      performance {
        raft_multiplier = 1
      }

      # Enable local script checks
      enable_local_script_checks = true

      # Telemetry
      telemetry {
        prometheus_retention_time = "60s"
        disable_hostname = false
      }

%%s

  # Consul systemd service
  - path: /etc/systemd/system/%s.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Consul Agent
      Documentation=https://www.consul.io/
      Requires=network-online.target
      After=network-online.target
      ConditionFileNotEmpty=%s

      [Service]
      Type=notify
      User=%s
      Group=%s
      ExecStart=%s agent -config-dir=%s
      ExecReload=/bin/kill --signal HUP $MAINPID
      KillMode=process
      KillSignal=SIGTERM
      Restart=on-failure
      RestartSec=5
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target

  # Service registration for this VM
  - path: %s
    owner: %s:%s
    permissions: '%04o'
    content: |
      # VM service registration
      service {
        name = "kvm-guest"
        id = "kvm-%%s"
        port = %d
        tags = [%%s]

        meta = {
          "vm_name" = "%%s"
          "environment" = "%%s"
        }

        check {
          id = "ssh"
          name = "SSH Port Check"
          tcp = "localhost:%d"
          interval = "30s"
          timeout = "5s"
        }

        check {
          id = "system-health"
          name = "System Health"
          script = "/usr/bin/systemctl is-system-running --quiet || exit 1"
          interval = "60s"
          timeout = "10s"
        }
      }

# Final commands to enable and start Consul
runcmd:
  # Reload systemd and start Consul
  - systemctl daemon-reload
  - systemctl enable %s
  - systemctl start %s

  # Wait for Consul to start
  - sleep 5

  # Store environment info in Consul K/V (idempotent)
  - %s kv put nodes/%%s/hostname "%%s"
  - %s kv put nodes/%%s/environment "%%s"
  - %s kv put nodes/%%s/created "$(date -Iseconds)"

  # Verify Consul is running
  - systemctl status %s --no-pager || true
  - %s members || true

power_state:
  mode: reboot
  delay: now
  message: "Rebooting after Consul installation"
  timeout: 300
  condition: true
`,
		// Hostname/FQDN (3 args)
		config.NodeName,
		config.NodeName,
		config.Datacenter,

		// Install Consul binary (4 args)
		consul.ConsulDefaultVersion,
		consul.ConsulDefaultVersion,
		binaryDir,
		consul.ConsulBinaryPath,

		// Create Consul directories (3 args)
		consul.ConsulConfigDir,
		consul.ConsulOptDir,
		consul.ConsulLogDir,

		// Create consul user (11 args)
		consul.ConsulConfigDir,
		consul.ConsulUser,
		consul.ConsulUser,
		consul.ConsulGroup,
		consul.ConsulConfigDir,
		consul.ConsulUser,
		consul.ConsulGroup,
		consul.ConsulOptDir,
		consul.ConsulUser,
		consul.ConsulGroup,
		consul.ConsulLogDir,

		// Consul configuration file (7 args + content placeholders)
		consul.ConsulConfigFile,
		consul.ConsulUser,
		consul.ConsulGroup,
		consul.ConsulConfigPerm,
		consul.ConsulOptDir,
		consul.ConsulLogDir,
		config.LogLevel,

		// Systemd service (6 args)
		consul.ConsulServiceName,
		consul.ConsulConfigFile,
		consul.ConsulUser,
		consul.ConsulGroup,
		consul.ConsulBinaryPath,
		consul.ConsulConfigDir,

		// Service registration (5 args)
		servicesHCLPath,
		consul.ConsulUser,
		consul.ConsulGroup,
		consul.ConsulConfigPerm,
		shared.PortSSH,
		shared.PortSSH,

		// Final runcmd (7 args)
		consul.ConsulServiceName,
		consul.ConsulServiceName,
		consul.ConsulBinaryPath,
		consul.ConsulBinaryPath,
		consul.ConsulBinaryPath,
		consul.ConsulServiceName,
		consul.ConsulBinaryPath,
	)

	// Now format the cloud-init with dynamic values
	cloudInit = fmt.Sprintf(cloudInit,
		// Consul config HCL content placeholders
		config.NodeName,
		config.Environment,
		config.Datacenter,
		config.Datacenter,
		formatRetryJoin(config.RetryJoin),
		config.NodeName,
		config.NodeName,
		config.Environment,

		// Consul Connect configuration (optional)
		generateConsulConnectConfig(config.EnableConnect),

		// Service registration content placeholders
		config.NodeName,
		formatTags(config.Tags),
		config.NodeName,
		config.Environment,

		// K/V storage
		config.NodeName,
		config.NodeName,
		config.NodeName,
		config.Environment,
		config.NodeName,
	)

	logger.Info("Generated Consul cloud-init configuration",
		zap.String("node_name", config.NodeName),
		zap.Int("config_size", len(cloudInit)))

	return cloudInit, nil
}

// Helper functions

func formatRetryJoin(servers []string) string {
	if len(servers) == 0 {
		return ""
	}
	quoted := make([]string, len(servers))
	for i, server := range servers {
		quoted[i] = fmt.Sprintf(`"%s"`, server)
	}
	return strings.Join(quoted, ", ")
}

func formatTags(tags []string) string {
	if len(tags) == 0 {
		return `"kvm-guest", "managed-by-eos"`
	}
	quoted := make([]string, len(tags))
	for i, tag := range tags {
		quoted[i] = fmt.Sprintf(`"%s"`, tag)
	}
	return strings.Join(quoted, ", ")
}

func generateConsulConnectConfig(enabled bool) string {
	if !enabled {
		return "  # Consul Connect disabled\n"
	}

	return fmt.Sprintf(`  # Enable Consul Connect
  connect {
    enabled = true
  }

  ports {
    grpc = %d
  }
`, consul.PortgRPC)
}
