services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eos-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
  command: ["start", "--optimized", "--http-enabled"] # replace start with start-dev here to start the server in development mode
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: changeme
      KC_PROXY: edge
      KC_HOSTNAME: hera.domain.com
    ports:
      - "8111:8080"
    depends_on:
      - postgres
    networks:
      - eos-network

volumes:
  pgdata:

networks:
  eos-network:
