services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eos-network
      
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: keycloak_user
      DB_PASSWORD: changeme
    ports:
      - "8111:8080"
    depends_on:
      - postgres
    networks:
      - eos-network

volumes:
  pgdata:
  
networks:
  eos-network:
