services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9080:8080"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
    networks:
      - eos-network
      
volumes:
  jenkins_home:

networks:
  eos-network:
