---
- name: Deploy and run Docker installation script
  hosts: docker_hosts
  become: yes  # run tasks as root
  tasks:
    - name: Copy deploy_docker.py to remote host
      copy:
        src: deploy_docker.py
        dest: /tmp/deploy_docker.py
        mode: '0755'

    - name: Execute the deploy_docker.py script
      command: /tmp/deploy_docker.py
      register: deploy_result

    - name: Display output from deploy_docker.py
      debug:
        var: deploy_result.stdout_lines
