---
- name: Disable SSH root login on remote hosts
  hosts: all
  become: yes
  tasks:
    - name: Backup the SSH configuration file
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: yes
        backup: yes
      # Using the copy module with remote_src ensures we copy the file from the remote host.

    - name: Ensure PermitRootLogin is set to "no" in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?\s*PermitRootLogin\s+'
        line: 'PermitRootLogin no'
        state: present
        backup: yes
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      # This handler attempts to restart the SSH service using several common commands.
      shell: |
        systemctl restart sshd || systemctl restart ssh || service sshd restart || service ssh restart
      become: yes
