---
- name: Add Backup Host Fingerprint to Known Hosts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ensure fingerprints of the all hosts to local known_hosts file
      known_hosts:
        path: "~/.ssh/known_hosts"
        name: "{{ ansible_host | default(inventory_hostname) }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' ~ (ansible_host | default(inventory_hostname))) }}"
      delegate_to: localhost
