database:
  name: "eos_db"
  user: "eos_user"
  host: "localhost"
  port: "5432"
  version: "16"
  socketDir: "/var/run/postgresql"
  tables:
    - "configuration"
    - "logs"

logging:
  level: "INFO"
  file: "/var/log/app.log"

logLevel:
	DebugLevel: "DEBUG"
	InfoLevel : "INFO"
	WarnLevel : "WARN"
	ErrorLevel: "ERROR"
	CriticalLevel: "CRITICAL"
	FatalLevel: "FATAL"

logPriority:
  DebugLevel: "0"
  InfoLevel: "1"
  WarnLevel: "2"
  ErrorLevel: "3"
  CriticalLevel: "4"
  FatalLevel: "5"

colourMap:
  DebugLevel: "\033[0;36m" # Cyan
  InfoLevel: "\033[0;32m"  # Green
  WarnLevel: "\033[0;33m"  # Yellow
  ErrorLevel: "\033[0;31m" # Red
  CriticalLevel: "\033[0;35m" # Magenta
  FatalLevel: "\033[1;31m" # Bright Red