database:
  name: "eos_db"
  user: "eos_user"
  host: "localhost"
  port: "5432"
  version: "16"
  socketDir: "/var/run/postgresql"
  tables:
    - "configuration"
    - "logs"

logging:
  level: "INFO"
  file: "/var/log/cyberMonkey/eos.log"

logLevel:
  Debug:
    - logPriority: "0"
    - colourMap: "\033[0;36m"
  Info:
    - logPriority: "1"
    - colourMap: "\033[0;32m" 
  Warn:
    - logPriority: "2"
    - colourMap: "\033[0;33m"
  Error:
    - logPriority: "3"
    - colourMap: "\033[0;31m"
  Critical:
    - logPriority: "4"
    - colourMap: "\033[0;35m"
  Fatal:
    - logPriority: "5"
    - colourMap: "\033[1;31m"

reset:
  colour: "\033[0m"