services:
  postgresql:
    image: postgres:latest
    container_name: hera-postgresql
    restart: always
    environment:
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: authentik
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - arachne-net

  redis:
    image: redis:alpine
    container_name: hera-redis
    restart: always
    volumes:
      - redis:/data
    networks:
      - arachne-net


  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    container_name: hera-authentik
    restart: always
    depends_on:
      - postgresql
      - redis
    environment:
      AUTHENTIK_SECRET_KEY: "changeme1"
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: changeme
      AUTHENTIK_REDIS__HOST: redis
    ports:
      - "8243:9000"  # internal admin and UI
      - "8263:9443"  # reverse proxy (optional, TLS)
    volumes:
      - media:/media
      - custom-templates:/templates
    networks:
      - arachne-net

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: hera-authentic-worker
    restart: always
    depends_on:
      - authentik-server
    environment:
      AUTHENTIK_SECRET_KEY: "change_this_secret_key"
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: changeme
      AUTHENTIK_REDIS__HOST: redis
    volumes:
      - media:/media
      - custom-templates:/templates
    networks:
      - arachne-net

volumes:
  postgresql:
  redis:
  media:
  custom-templates:

networks:
  arachne-net:
    external: true
