services:
  postgresql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: changeme  # change this
      POSTGRES_DB: authentik
    volumes:
      - postgresql:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data

  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    depends_on:
      - postgresql
      - redis
    environment:
      AUTHENTIK_SECRET_KEY: "change_this_secret_key"
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: changeme
      AUTHENTIK_REDIS__HOST: redis
    ports:
      - "9000:9000"  # internal admin and UI
      - "9443:9443"  # reverse proxy (optional, TLS)
    volumes:
      - media:/media
      - custom-templates:/templates

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    depends_on:
      - authentik-server
    environment:
      AUTHENTIK_SECRET_KEY: "change_this_secret_key"
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: changeme
      AUTHENTIK_REDIS__HOST: redis
    volumes:
      - media:/media
      - custom-templates:/templates

volumes:
  postgresql:
  redis:
  media:
  custom-templates:
