services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"        # Web interface
      - "8920:8920"        # (Optional) HTTPS
    volumes:
      - ./config:/config    # Configuration files
      - ./cache:/cache      # Cache
      - ./media:/media      # Media library
    restart: always
    networks:
      - arachne-net
      
volumes:
  db-data:

networks:
  arachne-net: 
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-arachne
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/22
        - subnet: fd42:1a2b:3c4d:5e6f::/64
