services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8059:8080"   # For the Jenkins web UI
      - "9059:50000"  # For inbound agent connections
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
    networks:
      - arachne-net
      
volumes:
  jenkins_home:
    name: jenkins_home

networks:
  arachne-net:
    external: true
