# stackstorm-webhook.yml
# /opt/stackstorm/packs/delphi/rules/wazuh_webhook.yml
# sudo st2ctl reload --register-all
---
name: wazuh_webhook
pack: delphi
description: "Catch POSTs from Wazuh and trigger pipeline"
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: wazuh_alert
criteria:
  trigger.body.rule.level:
    type: "greaterthan"
    pattern: 2
action:
  ref: core.local
  parameters:
    cmd: |
      #— send into our DB loader (with dedupe) —
      echo '{{ trigger.body | to_json_string }}' \
        | /usr/local/bin/alert-to-db.py
      #— also dump the raw JSON for debugging —
      echo '{{ trigger.body | to_json_string }}' \
        >> /var/log/stackstorm/wazuh_alerts.log
