services:
  umami:
    image: ghcr.io/umami-software/umami:latest
    container_name: umami
    ports:
      - "8117:3000"  # Adjust if needed
    environment:
      # URL to connect to your PostgreSQL database
      DATABASE_URL: "postgresql://umami:umami@db:5432/umami"
      # Optional: Set the port Umami should listen on
      PORT: "3000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - arachne-net
      
  db:
    image: postgres
    container_name: umami-db
    environment:
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: umami
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - arachne-net

volumes:
  db_data:

networks:
  arachne-net: 
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-arachne
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/22
        - subnet: fd42:1a2b:3c4d:5e6f::/64

