services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    ports:
      - "8117:3000"  # Adjust if needed
    environment:
      DATABASE_URL: "postgresql://umami:changeme@db:5432/umami"
      DATABASE_TYPE: postgresql
      APP_SECRET: changeme
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8117/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - arachne-net
      
  db:
    image: postgres:15-alpine
    container_name: umami-db
    environment:
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: umami
    volumes:
      - umami_db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - arachne-net

volumes:
  umami_db_data:

networks:
  arachne-net:
    external: true

