services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki_db
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: wiki_user
    logging:
      driver: "none"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - arachne-net
      
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wiki_user
      DB_PASS: changeme
      DB_NAME: wiki_db
    restart: always
    ports:
      - "11080:3000"
    networks:
      - arachne-net
      
volumes:
  db-data:

networks:
  arachne-net: 
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-arachne
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/22
        - subnet: fd42:1a2b:3c4d:5e6f::/64
