services:
  mysql-server:
    image: mysql:latest
    container_name: zabbix-mysql
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: changeme1
    volumes:
      - zabbix-db:/var/lib/mysql
    restart: always
    networks:
      - arachne-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: changeme
    depends_on:
      - mysql-server
    ports:
      - "8233:10051"
    restart: always
    networks:
      - arachne-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: changeme
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Australia/Perth
    ports:
      - "8237:8080"
    depends_on:
      - mysql-server
      - zabbix-server
    restart: always
    networks:
      - arachne-net

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-server
    restart: always
    networks:
      - arachne-net

volumes:
  zabbix-db:

networks:
  arachne-net:
    external: true
