---
- name: Update system and schedule daily updates
  hosts: centos
  become: yes
  vars:
    # Generate a random hour (0-23) and minute (0-59)
    cron_hour: "{{ range(0, 24) | random }}"
    cron_minute: "{{ range(0, 60) | random }}"

  tasks:
    - name: Update all packages immediately
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Schedule daily system update cron job
      cron:
        name: "Daily system update"
        minute: "{{ cron_minute }}"
        hour: "{{ cron_hour }}"
        job: "/usr/bin/yum update -y && /usr/bin/yum autoremove -y && /usr/bin/yum clean all"
