// pkg/hecate/lifecycle_compat.go
// Compatibility shim for old lifecycle_create.go code that uses GenerateCompleteHecateStack
// TODO: Migrate lifecycle_create.go to use GenerateFromYAML instead

package hecate

import (
	"fmt"
	"path/filepath"

	"github.com/CodeMonkeyCybersecurity/eos/pkg/crypto"
	"github.com/CodeMonkeyCybersecurity/eos/pkg/eos_io"
	"github.com/CodeMonkeyCybersecurity/eos/pkg/eos_unix"
	"github.com/uptrace/opentelemetry-go-extra/otelzap"
	"go.uber.org/zap"
)

// GenerateCompleteHecateStack generates a complete docker-compose.yml with all Hecate components
// DEPRECATED: Use GenerateFromYAML with YAML config instead
func GenerateCompleteHecateStack(rc *eos_io.RuntimeContext, domain string) error {
	logger := otelzap.Ctx(rc.Ctx)
	logger.Info("Generating complete Hecate docker-compose stack")

	// ASSESS - Check if /opt/hecate exists
	if err := eos_unix.MkdirP(rc.Ctx, BaseDir, 0o755); err != nil {
		return fmt.Errorf("failed to create base directory %s: %w", BaseDir, err)
	}

	// Create required subdirectories (minimal stack)
	dirs := []string{
		filepath.Join(BaseDir, "logs/caddy"),
		filepath.Join(BaseDir, "media"),
		filepath.Join(BaseDir, "custom-templates"),
		filepath.Join(BaseDir, "authentik/blueprints/custom"),
	}

	for _, dir := range dirs {
		if err := eos_unix.MkdirP(rc.Ctx, dir, 0o755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	logger.Info("Created directory structure", zap.String("base", BaseDir))

	// INTERVENE - Prompt for and generate bootstrap credentials
	bootstrapCreds, err := PromptAndGenerateBootstrapCredentials(rc)
	if err != nil {
		return fmt.Errorf("failed to generate bootstrap credentials: %w", err)
	}

	// Store bootstrap credentials in Consul (or will fall back to .env)
	if err := StoreBootstrapCredentials(rc, bootstrapCreds); err != nil {
		logger.Warn("Failed to store bootstrap credentials in Consul, will use .env fallback",
			zap.Error(err))
		// Not fatal - credentials will be in .env file
	}

	// INTERVENE - Generate secrets
	secrets, err := generateHecateSecretsLegacy(rc)
	if err != nil {
		return fmt.Errorf("failed to generate secrets: %w", err)
	}

	// Add bootstrap credentials to secrets struct
	secrets.AuthentikBootstrapEmail = bootstrapCreds.Email
	secrets.AuthentikBootstrapPassword = bootstrapCreds.Password
	secrets.AuthentikBootstrapToken = bootstrapCreds.Token

	// Generate .env file
	if err := generateEnvFileLegacy(rc, secrets); err != nil {
		return fmt.Errorf("failed to generate .env file: %w", err)
	}

	// Generate docker-compose.yml
	if err := generateDockerComposeLegacy(rc); err != nil {
		return fmt.Errorf("failed to generate docker-compose.yml: %w", err)
	}

	// Generate Caddyfile
	if err := GenerateMinimalCaddyfile(rc, domain); err != nil {
		return fmt.Errorf("failed to generate Caddyfile: %w", err)
	}

	// EVALUATE - Verify files were created
	requiredFiles := []string{
		filepath.Join(BaseDir, "docker-compose.yml"),
		filepath.Join(BaseDir, ".env"),
		filepath.Join(BaseDir, "Caddyfile"),
	}

	for _, file := range requiredFiles {
		if !eos_unix.FileExists(file) {
			return fmt.Errorf("verification failed: %s not created", file)
		}
	}

	logger.Info("Successfully generated Hecate stack files",
		zap.String("location", BaseDir))

	return nil
}

// generateHecateSecretsLegacy generates all required secrets for Hecate (legacy single-domain mode)
func generateHecateSecretsLegacy(rc *eos_io.RuntimeContext) (*HecateSecrets, error) {
	logger := otelzap.Ctx(rc.Ctx)
	logger.Info("Generating secrets for Hecate services (alphanumeric-only)")

	// Generate strong alphanumeric-only passwords for maximum compatibility
	pgPass, err := crypto.GenerateURLSafePassword(32)
	if err != nil {
		return nil, fmt.Errorf("failed to generate PostgreSQL password: %w", err)
	}

	authentikKey, err := crypto.GenerateURLSafePassword(50)
	if err != nil {
		return nil, fmt.Errorf("failed to generate Authentik secret key: %w", err)
	}

	secrets := &HecateSecrets{
		PGPass:                 pgPass,
		PGUser:                 "authentik",
		PGDatabase:             "authentik",
		AuthentikSecretKey:     authentikKey,
		AuthentikTag:           "2024.8.3",
		ComposePortHTTP:        "9000",
		ComposePortHTTPS:       "9443",
		AuthentikWorkerThreads: "4",
	}

	logger.Info("Generated secrets for Hecate services")
	return secrets, nil
}

// generateEnvFileLegacy creates the .env file with secrets (legacy mode)
func generateEnvFileLegacy(rc *eos_io.RuntimeContext, secrets *HecateSecrets) error {
	logger := otelzap.Ctx(rc.Ctx)
	logger.Info("Generating .env file")

	envContent := fmt.Sprintf(`# Hecate Environment Configuration
# Generated by Eos

# PostgreSQL Configuration
PG_PASS=%s
POSTGRES_USER=%s
POSTGRES_DB=%s

# Authentik Configuration
AUTHENTIK_SECRET_KEY=%s
AUTHENTIK_TAG=%s
AUTHENTIK_IMAGE=ghcr.io/goauthentik/server
AUTHENTIK_WORKER__THREADS=%s

# Authentik Bootstrap Credentials
# These are used for initial admin user creation
AUTHENTIK_BOOTSTRAP_EMAIL=%s
AUTHENTIK_BOOTSTRAP_PASSWORD=%s
AUTHENTIK_BOOTSTRAP_TOKEN=%s

# Compose Port Configuration
COMPOSE_PORT_HTTP=%s
COMPOSE_PORT_HTTPS=%s
`,
		secrets.PGPass,
		secrets.PGUser,
		secrets.PGDatabase,
		secrets.AuthentikSecretKey,
		secrets.AuthentikTag,
		secrets.AuthentikWorkerThreads,
		secrets.AuthentikBootstrapEmail,
		secrets.AuthentikBootstrapPassword,
		secrets.AuthentikBootstrapToken,
		secrets.ComposePortHTTP,
		secrets.ComposePortHTTPS,
	)

	envPath := filepath.Join(BaseDir, ".env")
	if err := eos_unix.WriteFile(rc.Ctx, envPath, []byte(envContent), 0600, ""); err != nil {
		return fmt.Errorf("failed to write .env file: %w", err)
	}

	logger.Info("Generated .env file", zap.String("path", envPath))
	return nil
}

// generateDockerComposeLegacy creates the docker-compose.yml file with minimal stack (legacy mode)
func generateDockerComposeLegacy(rc *eos_io.RuntimeContext) error {
	logger := otelzap.Ctx(rc.Ctx)
	logger.Info("Generating docker-compose.yml (minimal stack: Caddy + Authentik)")

	composeContent := `services:

  caddy:
    image: caddy:latest
    container_name: hecate-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./logs/caddy:/var/log/caddy:rw
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - hecate-net

  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${POSTGRES_USER:-authentik}
      POSTGRES_DB: ${POSTGRES_DB:-authentik}
    env_file:
      - .env
    networks:
      - hecate-net

  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    networks:
      - hecate-net

  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.8.3}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_WORKER__THREADS: ${AUTHENTIK_WORKER__THREADS:-4}
      AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD}
      AUTHENTIK_BOOTSTRAP_EMAIL: ${AUTHENTIK_BOOTSTRAP_EMAIL}
      AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_BOOTSTRAP_TOKEN}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
      - ./authentik/blueprints/custom:/blueprints/custom
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - hecate-net

  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.8.3}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_WORKER__THREADS: ${AUTHENTIK_WORKER__THREADS:-4}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
      - ./authentik/blueprints/custom:/blueprints/custom
    env_file:
      - .env
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - hecate-net

networks:
  hecate-net:
    driver: bridge

volumes:
  database:
    driver: local
  redis:
  caddy_data:
  caddy_config:
`

	composePath := filepath.Join(BaseDir, "docker-compose.yml")
	if err := eos_unix.WriteFile(rc.Ctx, composePath, []byte(composeContent), 0644, ""); err != nil {
		return fmt.Errorf("failed to write docker-compose.yml: %w", err)
	}

	logger.Info("Generated docker-compose.yml", zap.String("path", composePath))
	return nil
}
