services:
  postgres:
    image: postgres
    container_name: hera-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eos-network

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: [
      "start",
      "--https-port=8443",
      "--https-certificate-file=/etc/x509/https/tls.crt",
      "--https-certificate-key-file=/etc/x509/https/tls.key",
      "--optimized",
      "--verbose"
    ]
    container_name: hera-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: changeme
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://hera-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: changeme
      KC_HOSTNAME: hera.domain.com
      KC_EXTERNAL_URL: "https://hera.domain.com"
    ports:
      - "8111:8443"
    depends_on:
      - postgres
    volumes:
      - ./certs:/etc/x509/https:ro
    networks:
      - eos-network

volumes:
  pgdata:

networks:
  eos-network:
