---
- name: Configure Docker host for Wazuh Docker event monitoring
  hosts: endpoints
  become: yes
  gather_facts: yes

  tasks:
    - name: Install python3 and python3-pip if not present
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install required Python packages for Docker integration
      pip:
        name:
          - docker==7.1.0
          - urllib3==1.26.20
          - requests==2.32.2
        extra_args: "--break-system-packages"
        executable: pip3

    - name: Ensure Wazuh agent configuration directory exists
      file:
        path: /var/ossec/etc
        state: directory

    - name: Configure docker-listener in ossec.conf
      blockinfile:
        path: /var/ossec/etc/ossec.conf
        marker: "<!-- {mark} ANSIBLE DOCKER LISTENER CONFIG -->"
        block: |
          <wodle name="docker-listener">
            <disabled>no</disabled>
          </wodle>
        insertafter: '</ossec_config>'
      notify: Restart Wazuh Agent

  handlers:
    - name: Restart Wazuh Agent
      systemd:
        name: wazuh-agent
        state: restarted
