---
- name: Install osquery on Ubuntu/Debian systems
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    # Map ansible_architecture to repo arch value.
    osquery_arch: >-
      {% if ansible_architecture == "x86_64" %}
      amd64
      {% elif ansible_architecture == "aarch64" %}
      arm64
      {% else %}
      unsupported
      {% endif %}

  tasks:
    - name: Fail if unsupported distribution
      fail:
        msg: "This playbook supports only Ubuntu and Debian (detected {{ ansible_distribution }})"
      when: ansible_distribution not in ["Ubuntu", "Debian"]

    - name: Fail if unsupported architecture
      fail:
        msg: "Architecture {{ ansible_architecture }} is not supported by this playbook."
      when: osquery_arch == "unsupported"

    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download osquery GPG key
      get_url:
        url: "https://pkg.osquery.io/deb/pubkey.gpg"
        dest: /etc/apt/keyrings/osquery.asc
        mode: '0644'
        force: yes

    - name: Add osquery repository file
      copy:
        dest: /etc/apt/sources.list.d/osquery.list
        content: "deb [arch={{ osquery_arch }} signed-by=/etc/apt/keyrings/osquery.asc] https://pkg.osquery.io/deb deb main\n"
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install osquery package
      apt:
        name: osquery
        state: present
