---
- name: Update Docker listener configuration in ossec.conf
  hosts: endpoints
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure Wazuh agent configuration directory exists
      file:
        path: /var/ossec/etc
        state: directory

    - name: Remove old docker-listener block if it exists
      replace:
        path: /var/ossec/etc/ossec.conf
        # Remove any block that starts with <wodle name="docker-listener"> and contains an interval of 10m
        regexp: '(?s)<wodle name="docker-listener">\s*<interval>10m</interval>.*?</wodle>\s*'
        replace: ''
      notify: Restart Wazuh Agent

    - name: Insert updated docker-listener block at the end of ossec.conf
      blockinfile:
        path: /var/ossec/etc/ossec.conf
        marker: "<!-- {mark} ANSIBLE DOCKER LISTENER CONFIG -->"
        block: |
          <!-- Docker listener integration -->
          <wodle name="docker-listener">
              <interval>6m</interval>
              <attempts>5</attempts>
              <run_on_start>yes</run_on_start>
              <disabled>no</disabled>
          </wodle>
        insertafter: EOF
      notify: Restart Wazuh Agent

  handlers:
    - name: Restart Wazuh Agent
      systemd:
        name: wazuh-agent
        state: restarted
