---
- name: Update Docker listener configuration in ossec.conf
  hosts: endpoints
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure Wazuh agent configuration directory exists
      file:
        path: /var/ossec/etc
        state: directory

    - name: Remove unmanaged docker-listener block with old settings if present
      replace:
        path: /var/ossec/etc/ossec.conf
        # This regex looks for a docker-listener block with an interval set to 10m.
        regexp: '(?s)<wodle\s+name="docker-listener">\s*<interval>10m</interval>.*?</wodle>\s*'
        replace: ''
      notify: Restart Wazuh Agent

    - name: Ensure updated docker-listener block is present in ossec.conf
      blockinfile:
        path: /var/ossec/etc/ossec.conf
        marker: "<!-- Docker listener integration -->"
        block: |
          <ossec_config>
            <wodle name="docker-listener">
                <interval>6m</interval>
                <attempts>5</attempts>
                <run_on_start>yes</run_on_start>
                <disabled>no</disabled>
            </wodle>
          </ossec_config>
        insertafter: EOF
      notify: Restart Wazuh Agent

  handlers:
    - name: Restart Wazuh Agent
      systemd:
        name: wazuh-agent
        state: restarted
