---
- name: Fetch Docker ps output from remote hosts and save locally
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Run docker ps command on remote host
      command: docker ps
      register: docker_ps_output
      changed_when: false

    - name: Ensure local directory /data/getDockerPs exists
      delegate_to: localhost
      file:
        path: /opt/data/getDockerPs
        state: directory
        mode: '0755'
      run_once: true

    - name: Save docker ps output to local file
      delegate_to: localhost
      copy:
        content: "{{ docker_ps_output.stdout }}"
        dest: "/opt/data/getDockerPs/{{ inventory_hostname }}_docker_ps.txt"
      when: docker_ps_output.stdout is defined
