services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki_db
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: wiki_user
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - eos-network
      
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wiki_user
      DB_PASS: wikijsrocks
      DB_NAME: wiki_db
    restart: unless-stopped
    ports:
      - "11080:3000"
    networks:
      - eos-network
      
volumes:
  db-data:

networks:
  eos-network:
