services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "8069:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      # These are optional. They set the default admin credentials.
      GF_SECURITY_ADMIN_USER: admin                                     # <- Change these values
      GF_SECURITY_ADMIN_PASSWORD: adminPleaseChange123#Me               # <-
      GF_LOG_LEVEL: debug                                               # Change for production
      GF_SERVER_ROOT_URL: http://my.grafana.server/                     # <-
      GF_PLUGINS_PREINSTALL: grafana-clock-panel, grafana-simple-json-datasource
    networks:
      - eos-network
  
networks:
  eos-network:
