services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:
    restart: always
