services:
  postgres:
    image: postgres
    container_name: hera-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eos-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start", "--http-enabled"]  # For production, you can use "--optimized" if desired.
    container_name: hera-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: changeme
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://hera-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: changeme
      # Removed deprecated KC_PROXY
      KC_HOSTNAME: hera.domain.com
      KC_HTTP_ENABLED: "true"
      KC_EXTERNAL_URL: "https://hera.domain.com"
    ports:
      - "8111:8080"
    depends_on:
      - postgres
    networks:
      - eos-network

volumes:
  pgdata:

networks:
  eos-network:
