services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: mykeycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: change_me
    command: >
      start --db=postgres --features=token-exchange
      --db-url=<JDBC-URL> --db-username=<DB-USER> --db-password=<DB-PASSWORD>
      --https-key-store-file=<file> --https-key-store-password=<password>
