
version: '3'

services:
  traefik:
    image: "traefik:v2.10"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=henry@codemonkey.net.au"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/xenia.net.au/traefik.toml:/traefik.toml"
      - "./traefik/xenia.net.au/acme.json:/acme.json"
    networks:
      - "traefik-net"

networks:
  traefik-net:
    external: true
    