# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# This workflow is currently disabled in favor of label-simple.yml
# which doesn't require label creation permissions.

name: Labeler (Disabled)
on: 
  workflow_dispatch:
  # Disabled - use label-simple.yml instead
  # pull_request:
  #   types: [opened, edited, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Workflow disabled
        run: |
          echo "🏷️ This labeler workflow is disabled"
          echo "Using label-simple.yml instead which doesn't require label creation permissions"
          echo ""
          echo "To re-enable this workflow:"
          echo "1. Create repository labels: ./scripts/setup-github-labels.sh"
          echo "2. Uncomment the pull_request trigger above"
          echo "3. Disable label-simple.yml workflow"